name: a_dialog
version: 1.1.0
homepage: https://github.com/Mohamed-Nagdy/a_dialog
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: A Dialog Package Is For Show Awesome Dialogs With Simple Lines Of Code
environment: 
  sdk: '>=2.17.6 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  vector_math: ^2.1.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
