name: a_dialog
description: A Dialog Package Is For Show Awesome Dialogs With Simple Lines Of Code 
version: 1.0.1
homepage: https://github.com/Mohamed-Nagdy/a_dialog

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets
